version: "3.3"
services:
  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    stdin_open: true
    tty: true
    working_dir: /app

